baseURL = "https://simon020286.github.io/"
languageCode = "it-IT"
title = "Dev Daddy"
theme = "cactus"

defaultContentLanguage = "it"
disqusShortname = "devdaddy-1"

[params]
  colortheme = "dark" # dark, light, white, or classic
  favicon = ""
  site_logo = ""
  description = "Dev Daddy blog."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/full-stack-developers.jpg"
  recent_posts_number = 2

  tagsOverview = true
  [params.comments]
      enabled = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3